# Instructions to run:
# cd to folder containing this file
# conda env create
# source activate ml_hw1

name: ml_hw1
dependencies:
- python=3.6
- pandas>=0.19
- numpy>=1.11
- bokeh>=0.12
- scikit-learn>=0.18
- scipy>=0.18
- matplotlib>=2
- jupyter>=1.0
- ipython>=5
- virtualenv>=15
- seaborn

